### ISSUE TITLE
Latest heka fails to compile with kinesis plugin added

### ISSUE THREAD

**Issue by moritzheiber** [crewton/heka-plugins#1]
I tried compiling heka 0.10.0b2 with the kinesis plugin enabled and it failed with the following error output:

```
Scanning dependencies of target hekad
# github.com/crewton/heka-plugins/kinesis
heka/src/github.com/crewton/heka-plugins/kinesis/kinesis_output.go:73: not enough arguments in call to pack.Recycle
heka/src/github.com/crewton/heka-plugins/kinesis/kinesis_output.go:88: not enough arguments in call to pack.Recycle
heka/src/github.com/crewton/heka-plugins/kinesis/kinesis_output.go:91: not enough arguments in call to pack.Recycle
CMakeFiles/hekad.dir/build.make:49: recipe for target 'CMakeFiles/hekad' failed
make[2]: *** [CMakeFiles/hekad] Error 2
CMakeFiles/Makefile2:1645: recipe for target 'CMakeFiles/hekad.dir/all' failed
make[1]: *** [CMakeFiles/hekad.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

I scanned over the code and couldn't find anything obvious wrong with it. What do you think?

**Comment by eflee** [comment]
From the documentation:

> In contrast to the Input plugin API, and older versions of the Output plugin API, output plugin code should not call the PipelinePacks’ Recycle method when a message has completed its processing. Message recycling is now handled by the OutputRunner. 

From [the docs](http://hekad.readthedocs.org/en/latest/developing/plugin.html#transitional-filter-output-apis-for-v0-10-only)

It looks like this just needs to be removed.

**Comment by moritzheiber** [comment]
Ah! Good catch, I'll try this out and maybe even submit a patch later :)

**Comment by crewton** [comment]
Sorry about the lack of response. I didn't get a chance to bring this to the front of my queue, since we're no longer using it.

I'm glad you were able to get it figured out!
